import * as fs from 'fs';
import * as path from 'path';
import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type { WikiConfig } from './config';

type Overrides = Partial<Omit<Config, 'themeConfig'>> & {
  themeConfig?: Record<string, unknown>;
  /** The site root, for the icon existence checks. Defaults to the working directory, which is where Docusaurus reads the config. Tests pass it. */
  siteDir?: string;
};

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function deepMerge<T extends Record<string, unknown>>(base: T, over: Record<string, unknown> | undefined): T {
  if (!over) return base;
  const out: Record<string, unknown> = { ...base };
  for (const [k, v] of Object.entries(over)) {
    out[k] = isPlainObject(v) && isPlainObject(out[k]) ? deepMerge(out[k] as Record<string, unknown>, v) : v;
  }
  return out as T;
}

/**
 * The whole Docusaurus config of a family wiki, built from wiki.config.json.
 *
 * An instance's docusaurus.config.ts is three lines: import the JSON, import this,
 * export the result. Per-wiki additions (navbar items, footer links, a plugin of its
 * own) go in `overrides`: `themeConfig` deep-merges onto the defaults, every other
 * key replaces its default.
 */
export function defineWikiConfig(wiki: WikiConfig, overrides: Overrides = {}): Config {
  const { themeConfig: themeOverrides, siteDir, ...configOverrides } = overrides;
  // Docusaurus reads the config from the site root, so that is where `static/` is.
  const root = siteDir ?? process.cwd();
  const hasStatic = (rel: string) => fs.existsSync(path.join(root, 'static', rel));

  const base: Config = {
    title: wiki.title,
    tagline: wiki.tagline,
    favicon: 'img/favicon.png',

    url: wiki.url,
    baseUrl: '/',

    organizationName: wiki.organizationName,
    projectName: wiki.projectName,

    onBrokenLinks: 'throw',

    // Rust toolchain (Rspack + SWC) instead of webpack + Babel. Cuts cold build
    // time roughly in half. Safe because the preset's plugins use only
    // getThemePath (no configureWebpack / Babel hooks) and there are no custom
    // Babel plugins. Requires @docusaurus/faster in the instance.
    future: {
      v4: true,
      faster: true,
    },

    markdown: {
      hooks: {
        onBrokenMarkdownLinks: 'warn',
      },
    },

    i18n: {
      defaultLocale: 'en',
      locales: ['en'],
    },

    headTags: [
      // Docusaurus emits only the single `favicon` link, so everything an iOS home
      // screen or an install prompt needs is declared here. The manifest is
      // written at build time by the manifest plugin, and the edge gate has to
      // exempt `.webmanifest` separately from `.json`: see the middleware matcher.
      //
      // Each icon link is declared only when its file exists under static/img, the
      // same rule the manifest plugin applies to its own entries. A wiki that has not
      // run `wiki icons` yet otherwise ships three <link>s to 404s on every page, which
      // the first migration onto the package (pcs-wiki, 2026-09-13) surfaced as the only
      // difference in an otherwise identical build.
      ...(hasStatic('img/apple-touch-icon.png')
        ? [{ tagName: 'link', attributes: { rel: 'apple-touch-icon', sizes: '180x180', href: '/img/apple-touch-icon.png' } }]
        : []),
      ...(hasStatic('img/icon-192.png')
        ? [{ tagName: 'link', attributes: { rel: 'icon', type: 'image/png', sizes: '192x192', href: '/img/icon-192.png' } }]
        : []),
      ...(hasStatic('img/icon-512.png')
        ? [{ tagName: 'link', attributes: { rel: 'icon', type: 'image/png', sizes: '512x512', href: '/img/icon-512.png' } }]
        : []),
      { tagName: 'link', attributes: { rel: 'manifest', href: '/manifest.webmanifest' } },
      { tagName: 'meta', attributes: { name: 'theme-color', content: wiki.og?.bg ?? '#ffffff' } },
      ...(wiki.noindex
        ? [{ tagName: 'meta', attributes: { name: 'robots', content: 'noindex, nofollow' } }]
        : []),
    ],

    presets: [
      [
        'classic',
        {
          docs: {
            routeBasePath: '/',
            sidebarPath: './sidebars.ts',
            editUrl: undefined,
            showLastUpdateTime: false,
            showLastUpdateAuthor: false,
            // Filter folder index docs out of every autogenerated section.
            // Each category in sidebars.ts links to its section's index via
            // `link: { type: 'doc', id: 'X/index' }`, so the category header
            // IS the navigation to the index. Without this filter, Docusaurus
            // 3.10 also includes the index as a duplicate child entry.
            sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }: any) => {
              const items = await defaultSidebarItemsGenerator(args);
              const stripIndex = (list: any[]): any[] =>
                list
                  .filter((item) => !(item.type === 'doc' && typeof item.id === 'string' && item.id.endsWith('/index')))
                  .map((item) =>
                    item.type === 'category' && Array.isArray(item.items)
                      ? { ...item, items: stripIndex(item.items) }
                      : item,
                  );
              return stripIndex(items);
            },
          },
          blog: false,
          theme: {
            customCss: './src/css/custom.css',
          },
          sitemap: wiki.noindex ? false : undefined,
        } satisfies Preset.Options,
      ],
      // The family preset: search, changelog dates, og cards, manifest, share mirror, theme.
      // It comes AFTER classic on purpose: Docusaurus resolves @theme/<Component> against
      // the LAST theme that provides it, so this order is what lets the preset's SearchBar
      // and MDXComponents/A shadow theme-classic's. Reversed, the search trigger vanishes
      // and the link wrapper never runs, which the template retarget's parity diff caught
      // on 2026-09-13. The instance's own src/theme still wins over both.
      ['@supersuit/docusaurus-preset-wiki', { ...wiki }],
    ],

    themeConfig: {
      image: undefined,

      // Docusaurus already emits og:title/description/url/locale/image and the
      // twitter pair. These are the ones it does NOT, and their absence stays
      // invisible until a card renders wrong somewhere. Every card the og-image
      // plugin generates is 1200x630, so the dimensions are true for all of them.
      metadata: [
        { property: 'og:type', content: 'article' },
        { property: 'og:site_name', content: wiki.title },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
      ],
      navbar: {
        title: wiki.title,
        logo: undefined,
        items: [],
      },
      footer: {
        style: 'light',
        links: [],
        copyright: wiki.copyright,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
      colorMode: {
        defaultMode: 'light',
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
    } satisfies Preset.ThemeConfig,
  };

  const merged = { ...base, ...configOverrides } as Config;
  merged.themeConfig = deepMerge(base.themeConfig as Record<string, unknown>, themeOverrides);
  return merged;
}
